services:
  market-monitor-test:
    build: .
    platform: linux/amd64
    ports:
      - '3000:3000'
      - '8080:8080'
    volumes:
      # Named volume for database persistence
      - market-monitor-data:/app/data
    environment:
      # Database configuration
      - DB_PATH=/app/data

      # Security configuration
      - JWT_SECRET=${JWT_SECRET:-change_this_in_production}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET:-change_this_in_production}

      # Application configuration
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - NODE_ENV=production
      - SERVER_PORT=8080
      - UI_PORT=3000
      - HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:8080/api/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  market-monitor-data:
    driver: local
