[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log
pidfile=/var/run/supervisord.pid

[program:ui]
directory=/app/ui
command=node .output/server/index.mjs
environment=UI_PORT="%(ENV_UI_PORT)s",HOST="%(ENV_HOST)s",NODE_ENV="%(ENV_NODE_ENV)s",NUXT_SESSION_PASSWORD="%(ENV_NUXT_SESSION_PASSWORD)s"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
redirect_stderr=true

[program:server]
directory=/app/server
command=node dist/index.js
environment=SERVER_PORT="%(ENV_SERVER_PORT)s",DB_PATH="%(ENV_DB_PATH)s",NODE_ENV="%(ENV_NODE_ENV)s",JWT_SECRET="%(ENV_JWT_SECRET)s",REFRESH_TOKEN_SECRET="%(ENV_REFRESH_TOKEN_SECRET)s",LOG_LEVEL="%(ENV_LOG_LEVEL)s",UI_ORIGIN="%(ENV_UI_ORIGIN)s"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
redirect_stderr=true
